[project]
name = "workshop-1-module-2-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[duckdb]>=1.21.0",
    "duckdb>=1.4.4",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "requests>=2.32.5",
]
